CREATE TABLE USERS (
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(20),
PASSWORD VARCHAR2(1000),
USERTYPE VARCHAR2(20)
);

CREATE OR REPLACE FUNCTION GET_ID(USERTYPE VARCHAR2)
RETURN NUMBER
IS

vID NUMBER;
USERTYPE_ID VARCHAR2(10) := '';


BEGIN
SELECT MAX(ID) INTO vID
FROM USERS
WHERE USERS.USERTYPE = USERTYPE;

IF USERTYPE = 'General'
THEN USERTYPE_ID := '11';
ELSIF USERTYPE = 'Premium'
THEN USERTYPE_ID := '12';
ELSIF USERTYPE = 'VIP'
THEN USERTYPE_ID := '13';
END IF;

IF vID = NULL
THEN vID := TO_NUMBER(CONCAT(USERTYPE_ID,'001'));
ELSE
vID := vID +1;
END IF;

RETURN vID;

END;
/




CREATE OR REPLACE TRIGGER SET_ID
BEFORE INSERT ON USERS
FOR EACH ROW

BEGIN
:NEW.ID := GET_ID(:NEW.USERTYPE);

END;
/

INSERT INTO USERS (NAME, PASSWORD, USERTYPE) VALUES ('SHEETAB', '123456', 'General');